# -*- coding: utf-8 -*-
"""Workshop2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WX9G0xmaUrgC4_9QGW_wYeMcgkDivYXX
"""

# Problem 1 - bank.csv
import pandas as pd

df = pd.read_csv("bank.csv")
object_cols = df.select_dtypes(include=['object']).columns
df_numeric = df.drop(columns=object_cols)
df_numeric.to_csv("banknumericdata.csv", index=False)
df_numeric2 = pd.read_csv("banknumericdata.csv")
print(df_numeric2.describe())

# Problem 2 - medical_students_dataset.csv
import pandas as pd

df = pd.read_csv("medical_students_dataset.csv")
for col in df.columns:
    if df[col].dtype != 'object':
        df[col].fillna(df[col].mean(), inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)
df = df.drop_duplicates()
print(df.head())

# Problem 3 - Titanic Dataset : Fare stats of Pclass = 1
import pandas as pd

titanic = pd.read_csv("/content/Titanic-Dataset.csv")
subset = titanic[['Name','Pclass','Sex','Age','Fare','Survived']]
subset = subset[subset['Pclass'] == 1]
print(subset['Fare'].mean())
print(subset['Fare'].median())
print(subset['Fare'].max())
print(subset['Fare'].min())

# Problem 4 - Drop rows where Age is null
subset = subset.dropna(subset=['Age'])
print(subset.isnull().sum())
print(subset.head())

# Problem 5 - One Hot Encoding Embarked
titanic = pd.read_csv("/content/Titanic-Dataset.csv")
embarked_encoded = pd.get_dummies(titanic['Embarked'], prefix='Embarked')
titanic = pd.concat([titanic, embarked_encoded], axis=1)
titanic = titanic.drop(columns=['Embarked'])
print(titanic.head())

# Problem 6 - Mean survival by Sex (with visualization)
import pandas as pd
import matplotlib.pyplot as plt

titanic = pd.read_csv("/content/Titanic-Dataset.csv")
mean_survival = titanic.groupby('Sex')['Survived'].mean()
mean_survival.plot(kind='bar')
plt.xlabel("Sex")
plt.ylabel("Mean Survival Rate")
plt.show()

# Problem 7 - Survival by Sex and Embarked (visualization)
import seaborn as sns
sns.barplot(data=titanic, x="Embarked", y="Survived", hue="Sex")
plt.show()